name: 'calver-release-action'
description: 'GitHub Action to generate Calver release'
author: 'cho0o0'
inputs:
  github_token:
    required: true
    description: 'GitHub token to be used'
  dry_run:
    required: false
    default: 'false'
    description: 'Whether to publish a release or just print supposed version'
runs:
  using: node16
  main: 'dist/index.js'
