name: 'publish'
on:
  push:
    branches: [release]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cho0o0/calver-release-action@release
        id: calver
        with:
          dry_run: false
          github_token: ${{secrets.PAT}}
