name: 'release'
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: |
          npm install
          npm run build
          npm run package
      - name: release
        run: |
          git config --global user.email "me@cyan.technology"
          git config --global user.name "Cyan [Auto Commit]"
          git add -f dist
          git commit -am "release"
          git push -f origin release
