name: 'build-test'
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: |
          npm install
          npm run all
      - uses: ./
        with:
          dry_run: true
          github_token: ${{secrets.GITHUB_TOKEN}}
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: |
          npm install
          npm run build
          npm run package
      - name: release
        run: |
          git config --global user.email "me@cyan.technology"
          git config --global user.name "Cyan [Auto Commit]"
          git fetch --all
          git add -f dist
          git commit -am "release"
          git push origin --force main:release
